<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/createArticleView.css" >
    <title>Login en web de pelis</title>

</head>
<body>

    <header>
        <h2>Crea tu propio articulo</h2>
    </header>

    <nav>
        <a href="index.php">Inicio</a>
        <?php
            if(isset($_POST['addTrabajo']))
            echo '<h1>Se ha creado correctamente</h1>';
        ?>
    </nav>

    <main>
        <form action="index.php?addTrabajo" method="post" enctype="multipart/form-data">
            <input type="text" name="descriptionTrabajo" placeholder="Descripcion" required/>
            <input type="date" name="startDate" placeholder="Descripcion" required/>
            <input type="date" name="finishDate" placeholder="Descripcion" required/>
            <input type="number" name="sueldo" placeholder="sueldo" required/>
            <input type="submit" name="addTrabajo" value="Crear"/>
        </form>
    </main>
<?php
die();
?>
</html>