<!DOCTYPE html>
<html>
<head>
	<title>Trabajos</title>
	<link rel="stylesheet" href="./css/mainView.css" >
	<style>
		a{
			padding: 10px 10px;
		}
		article{
			border: 1px solid black;
			padding: 15px;
		}
	</style>
</head>
<body>

	<header>
		<h1>Trabajos</h1>
	</header>

	<nav>

		<a href="index.php">Inicio</a> -

		<?php

		//si la session existe
		if($_SESSION['user']->getName()=="")
			echo '<a href="index.php?login">crear perfil/loger perfil</a>';
		else{
			echo 'Bienvenido '.$_SESSION['user']->getName().' 
			<a href="index.php?login&logout">Salir</a>';
		}

		//crear articulos y editar rol si es admin
		if($_SESSION['user']->getRol() == '0'){
			echo '<a href="index.php?addTrabajo">Crear trabajo</a>';
			echo'<a href="index.php?login&editProfile">Editar Perfil</a>';
			echo'<a href="index.php?informes">Ver informes</a>';
			echo'<a href="index.php?addTrabajo&estado">Estado de los trabajos</a>';
		}
		?>

	</nav>
	<br/><br/>

	<main>
		
		<?php
			echo '<a href="index.php?jornada&addJornada='.$_SESSION['user']->getId().'">Iniciar jornada de trabajo</a> <br/> <br/><br/><br/>';
			if(isset($message)){
				// echo $message;
				// echo '<a href="index.php?jornada&addJornada&incidencia='.$_SESSION['user']->getId().'">Si</a>';
			}
			echo '<a href="index.php?jornada&close='.$_SESSION['user']->getId().'">Cerrar jornada de trabajo</a>';

			echo '<a href="index.php?jornada&cerrar='.$_SESSION['user']->getId().'">Cerrar jornada de trabajo</a>';
			
		?>
		<?php
			
			foreach($trabajos as $trabajo){
				echo '<article>';
				
				if($_SESSION['user']->getName()!=''){
					echo $trabajo->getDescription().'<br/>' ;
					echo '<a href="index.php?addTrabajo&addUser&addWork='.$trabajo->getIdTrabajo().'">añadirse al trabajo</a>';
					echo '<a href="index.php?addTrabajo&addUser&negateWork='.$trabajo->getIdTrabajo().'">Negarse al trabajo</a>';
				}
				
				echo '</article>';
			}
			
				
		?>

	




</body>
</html>