<!DOCTYPE html>
<html>
<head>
	<title>Mi lista de peliculas</title>
</head>
<body>
<h1>Mi lista de peliculas</h1>

<br/>
<a href="index.php">Inicio</a> -


<?php

if($_SESSION['user']->getName()=="")
	echo '<a href="index.php?login">Login</a>';
else{
	echo 'Hola '.$_SESSION['user']->getName().' 
	<a href="index.php?login&logout">Salir</a>';

}

?>

<form action="index.php" method="post">
	<input type="text" name="busqueda" placeholder="Titulo para la búsqueda">
	<input type="submit" value="Busca" name="Busca">
	
</form>

<?php

echo "<ul>";
if(count($pelis)>0){
	foreach($pelis as $item){
		echo '<li> <a href="./views/imagenes/'.$item->getLink().' ">'.' '.$item.' </a>  </li>';
	}
	
}
else{
	echo "Sin resultados";
}
echo "</ul>";
?>
</body>
</html>