<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/createArticleView.css" >
    <title>Login en web de pelis</title>

</head>
<body>

    <header>
        <h2>ñade tu pokemon</h2>
    </header>

    <nav>
        <a href="index.php">Inicio</a>
        <?php
            if(isset($_POST['insertPokemon']))
            echo '<h1>Se ha creado correctamente</h1>';
        ?>
    </nav>

    <main>
        <form action="index.php?addPokemon" method="post" enctype="multipart/form-data">
            <input type="text" name="namePokemon" placeholder="name" required/>
            <!-- <input type="text" name="typePokemon" placeholder="type"> -->
            <select name="typePokemon">
                <option value="fuego" selected>Fuego</option>
                <option value="agua" >Agua</option>
                <option value="planta">Planta</option>
            </select>
            <input type="file" name="fileToUpload" required />
            <input type="submit" name="insertPokemon" value="Crear"/>
        </form>
    </main>
<?php
die();
?>
</html>