<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/createArticleView.css" >
    <title>Login en web de pelis</title>

</head>
<body>

    <header>
        <h2>añade tu pokemon</h2>
    </header>

    <nav>
        <a href="index.php">Inicio</a>
    </nav>

    <main>
        

        <?php
            if($name == ''){
                echo '<form action="index.php?team" method="post" enctype="multipart/form-data">
               <input type="text" name="nameTeam" placeholder="name" required/> </br>
               <input type="submit" name="insertPokemon" value="Crear"/>
                </form>';
                
            }
            else{
                echo 'Para añadir: </br>';
                foreach($pokemon as $poke){
                    echo $poke->getName().'<a href="index.php?team&pokemon_id='.$poke->getIdPokemon().'">🤑</a></br>';
                }   
            }

            // if($teamAdded>0){
            // echo 'Ya añadidos: </br>';
            // foreach($teamAdded->getPokemon() as $poke){
            //     echo $poke->getName().'</br>';
            // } 
            // }
            
        ?> 
    </main>
<?php
die();
?>
</html>