<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/createArticleView.css" >
    <title>Login en web de pelis</title>

</head>
<body>

    <header>
        <h2>Crea tu propio articulo</h2>
    </header>

    <nav>
        <a href="index.php">Inicio</a>
    </nav>

    <main>
        <form action="index.php?createArticle" method="post" enctype="multipart/form-data">
            <input type="text" name="tituloArticle" placeholder="Titulo" required/>
            <textarea name="textArea" rows="10" cols="50" placeholder="Escribe tu articulo" required></textarea>
            <input type="file" name="fileToUpload" />
            <input type="submit" name="createArticle" value="Crear"/>
        </form>
    </main>
<?php
die();
?>
</html>