<!DOCTYPE html>
<html>
<head>
	<title>Blogs de perros</title>
	<style>
		section{
			display: flex;
			flex-wrap: wrap;
		}
		article{
			margin: 1% 3% ;
			width: 25%;
			border: 1px solid black;
			padding: 10px; 
		}
		article h1{
			color: red;
		}
		article div{
			border: 1px solid black;
		}
		h1{
			text-align : center;
		}
		b{
			color: black;
		}
	</style>
</head>
<body>
<h1>Blogs de perros</h1>

<a href="index.php">Inicio</a> -

<!-- si la session existe -->
<?php
if($_SESSION['user']->getName()=="")
	echo '<a href="index.php?login">Login</a>';
else{
	echo 'Bienvenido '.$_SESSION['user']->getName().' 
	<a href="index.php?login&logout">Salir</a>';
}
?>


<h1>Articulos</h1>

<!-- muestra los articulo -->
<?php
if(count($article)>0){
	echo "<section>";
	foreach($article as $item){
		echo "<article>";
			echo  " <a href='?article=".$item->getIdArticle()."'> <h1>".$item->getTittle(). "<b> ( ".$item->getDate()." ) </b> </h1> </a>";
			
			
		echo "</article>";
	}
	echo "</section>";
}
else{
	echo "Sin resultados";
}
// ?>
</body>
</html>