<!DOCTYPE html>
<html>
<head>
	<title>Blogs de perros</title>
	<link rel="stylesheet" href="./css/mainView.css" >
	
</head>
<body>

<header>
	<h1>Blogs de perros</h1>
</header>

<nav>

	<a href="index.php">Inicio</a> -

	<!-- si la session existe -->
	<?php
	if($_SESSION['user']->getRole() == 1){
		echo '<a href="index.php?createArticle">Crear Articulos</a>';
	}
	
	if($_SESSION['user']->getName()=="")
		echo '<a href="index.php?login">Login</a>';
	else{
		 echo 'Bienvenido '.$_SESSION['user']->getName().' 
		<a href="index.php?login&logout">Salir</a>';
	}
	?>

</nav>

<main>
<h2>Articulos</h2>
<!-- muestra los articulo -->
<?php
if(count($article)>0){
	echo "<section>";
	foreach($article as $item){
		
		echo "<article>";
			echo '<img src="./views/imagenes/'.$item->getImage().'"/>';
			echo  " <a href='?article=".$item->getIdArticle()."'> <h1>".$item->getTittle(). "<b> ( ".$item->getDate()." ) </b> </h1> </a>";
		echo "</article>";
	}
	echo "</section>";
}

// ?>
</main>

</body>
</html>