<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/createArticleView.css" >
    <title>Create Noticia</title>

</head>
<body>

    <header>
        <h2>Crea tu propio articulo</h2>
    </header>

    <nav>
        <a href="index.php">Inicio</a> --
        <?php
            if(isset($_POST['createArticle']))
            echo '<h1>Se ha creado correctamente</h1>';
        ?>
    </nav>

    <main>
        <form action="index.php?newNoticia" method="post">
            <input type="text" name="tituloNoticia" placeholder="Titulo" required/>
            <input type="text" name="url" placeholder="Url noticia" required/>
            <input type="submit" name="createArticle" value="Crear"/>
        </form>
    </main>
<?php
die();
?>
</html>