<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/loginView.css" >
    <title>Carrito</title>
</head>
<body>
    <header>
        <H1>Carrito</H1>
    </header>

    <nav>
        <a href="index.php">Inicio</a>
    </nav>

    <main>
    
    <?php
    
   		if(count($orderItems)>0){
            foreach($orderItems as $item){
                echo '<article>';
    
                echo $item->getProduct()->getName();
                echo ': ';
                echo $item->getProduct()->getPrecio();
                echo '€ x ';
                echo $item->getCantidad(); 
    
                echo '</article>';
            }
            echo '</br>Precio total = '.$precioFinal ;
            
            echo '</br><a href="index.php?carrito&confirmarPedido">Confirmar Pedido</a>';
        }
        else{
            echo 'No hay pedidos';
        }
        
		?>
        
    
    </main>
</body>
</html>