<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="./css/mainView.css" >
	<title>Pagina Web</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<style>
		section{
			display: flex;
			flex-flow: row wrap;
			
		}
		article{
			border : 1px solid black;
			width: 25%
		}
		article a{
			border : 1px solid black;
		}
		img{
			width: 80%;
			height: 300px;
		}
		nav{
			border:1px solid black;
			padding:5px;
			text-align:center;
		}
		footer{
			text-align: center;
			padding: 10px;
		}	
		footer a{
			border:1px solid black;
			padding: 5px;
		}

	</style>
	
</head>
<body>

	<header>
		<h1>Pagina Web</h1>
	</header>

	<nav>

		<a href="index.php">Inicio</a> -

		<?php
		//si la session existe
		if($_SESSION['user']->getName()=="")
			echo '<a href="index.php?login">Login</a>';
		else{
			echo 'Bienvenido '.$_SESSION['user']->getName().' 
			<a href="index.php?login&logout">Salir</a> -';
			echo '<a href="index.php?newProducto">Crear Producto</a>';
		}
		
		//enlace editar role solo si es admin
		if($_SESSION['user']->getRol()==0){
			echo'<a href="index.php?role">Editar Rol</a>';
		}
		
		echo '-<a href="index.php?carrito">🛒</a>';
		?>

	</nav>

	<h2>Productos</h2>
	<form action="index.php" method="get">
		<input type="text" name="nameProducto" placeholder="Busca tu produto" />
		<input type="submit"  value="buscar" />
	</form>

	<section>



		<?php
		if($productos > 0){
			foreach($productos as $producto){
				echo '<article>';	
					echo '<img src="./views/imagenes/'.$producto->getImage().'"/> <br>'; 
					echo '<h1>'.'<a href="'.$producto->getIdProducto().'">'.$producto->getName()."(".$producto->getAutor().")".'</a></h1>';	
					if($producto->getStock()!=0 && $_SESSION['user']->getName()!=""){
						echo '<a href="index.php?producto='.$producto->getIdProducto().'">+</a>';
					}
					echo 'Stock:'.$producto->getStock();
				echo '</article>';
			}
		}
		else{
			echo 'no hay productos';
		}
		
		?>


	</section>

	<footer>
		<?php
			for ($i = 1; $i <= $porductCount; $i++) {
				if(isset($_GET['nameProducto']) ){
					echo '<a href="index.php?nameProducto='.$_GET['nameProducto'].'&pagina='.''.$i.'">'.$i.'</a>';
				}
				else{
					echo '<a href="index.php?pagina='.$i.'">'.$i.'</a>';
				}
			}
		?>
	</footer>


</body>
</html>