<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/loginView.css" >
    <title>Crear sala</title>
</head>
<body>
    <header>
        <H1>Crea una sala</H1>
    </header>

    <nav>
        <a href="index.php">Inicio</a>
    </nav>

    <main>

        <div class="form">
            
            <form action="index.php?sala" method="post">
                <input type="text" name="nameSala" placeholder="Nombre de sala" required/>
                <input type="submit" name="addSala" value="Entrar"/>
            </form>
        </div>
    
       
    
    </main>
<!-- </body> -->
</html>