<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/login.css" >
    <title>Login en web</title>
</head>
<body>
    <header>
        <H1>Logeate o Registrate</H1>
    </header>

    <nav>
        <a href="index.php">Inicio</a>
    </nav>

    <main>

        <div class="form">
            <h2>Logeo</h2>
            <form action="index.php?login" method="post">
                <input type="text" name="user" placeholder="Usuario" required/>
                <input type="password" name="password" placeholder="Contraseña" required />
                <input type="submit" name="logeo" value="Entrar"/>
            </form>
        </div>

    
        <div class="form">
            <h2>Registro</h2>
            <form action="index.php?login" method="post">
                <input type="text" name="user" placeholder="Usuario" required/>
                <input type="password" name="password" placeholder="Contraseña" required/>
                <input type="password" name="password2" placeholder="Repite la contraseña" required/>
                <input type="submit" name="registro" value="Registro"/>
            </form>
        </div>


       

    </main>
</body>
</html>