<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="./css/mainView.css" >
	<title>Chat</title>
	<script>
	let refresh = document.getElementById('refresh');
	refresh.addEventListener('click', _ => {
            location.reload();
	})
</script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<style>
		header{
			text-align: center;
			font-size:20px
		}
		section{
			border: 1px solid black;
		}
		.connect{
			width : 100%;
			text-align: right;
		}
		nav a{
			padding:5px 50px;
			color: black;
			text-decoration:none;
		}
		form{
			padding-bottom: 10px;
		}
		article{
			padding: 5px;
			margin: 10px 0px;
			
		}
		article a{
			border : 1px solid black;
		}
		.chat {

			display: flex;
			flex-flow : row wrap;
			background-color: grey;
		}
		.chat article{
			border-radius: 10px;
			width: 49%;
			background-color: lightgrey;
		}
		nav{
			background-color: grey;
			padding:5px;
			text-align:center;
		}
		footer{
			text-align: right;
			padding: 10px;
			background-color: grey;
		}
		footer form{
			
			margin-right: 0px;
		}	
		form input[type="text"]{
			width : 10%;
		}
		span{
			font-size:11px;
		}
		section a{
			padding: 0px 10px;
		}
	</style>
	
</head>
<body>

	<header>
		<h1>Chat</h1>
	</header>

	<nav>

		<a href="index.php">Inicio</a> -

		<?php
		//si la session existe
		if($_SESSION['user']->getName()=="")
			echo '<a href="index.php?login">Login</a>';

		else{
			echo 'Bienvenido '.$_SESSION['user']->getName().' 
			<a href="index.php?login&logout">Salir</a> -';

			echo '<a href="index.php?sala">Crear Sala</a>';
		}
		
		
		?>

	</nav>

	<section class="connect">
		
		<?php
			echo '<article>';
			
			if(isset($_GET['checkTime'])){
				echo '<a href="index.php?login&checkTime&close">Ocultar</a> <br/>';
				foreach($usersConectedInfo as $user){	
					echo '<a href="index.php?sala&privateChat='.$user->getId().'"> "'.$user->getName().'🟢"</a>';
				}
			}
			else{
				echo  '<a href="index.php?login&checkTime">Conectados</a>';				
			}

			echo '</article>'; 
		
		?>

	</section>

	
	
		
	<nav>
	<?php
		if($salas>0){
			foreach($salas as $sala){	
				
				echo '<a href="index.php?sala&id_sala='.$sala->getIdSala().'"> "'.$sala->getName().'"</a>';
			}
		}
	?>
	</nav>
		
	<?php
	if(isset($_GET['sala'])){
	
	?>
	
	<section >

		<?php
			
			if($salaById->getMessages() != null ){
				
				foreach($salaById->getMessages() as $message){
					echo '<article>';
					echo '<b>'.$message->getUser().'</b>: '.$message->getMessage().' <span>'.$message->getDate().'</span>';
					echo '</article>'; 
					
				}
				
			}
			else{
				echo '<article>';
					echo 'no hay mensajes todavia';
				echo '</article>' ;
			}
							
		?>


	</section>

	<footer>
		<?php
		if($_SESSION['user']->getName()!=""){	
			echo '<form action="index.php?sala&id_sala='.$salaById->getIdSala().'" method="post">
			<input type="text" name="textChat" placeholder="habla..." required/>
			<input type="hidden" name="idSalaToMessage" value="'.$salaById->getIdSala().'" />
			<input type="submit" id="refresh" name="sendText" value="💬"/>
			</form>';

		}
	}
		?>
	</footer> 
    

	

	


</body>
</html>