<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="./css/mainView.css" >
	<title>Chat</title>
	<script>
	let refresh = document.getElementById('refresh');
	refresh.addEventListener('click', _ => {
            location.reload();
	})
</script>
	
	<link rel="stylesheet" href="./css/main.css" >
	
</head>
<body>

	<header>
		<h1>Chat</h1>
	</header>

	<nav>

		<a href="index.php">Inicio</a> -

		<?php
		//si la session existe
		if($_SESSION['user']->getName()=="")
			echo '<a href="index.php?login">Login</a>';

		else{
			echo 'Bienvenido '.$_SESSION['user']->getName().' 
			<a href="index.php?login&logout">Salir</a> -';

			echo '<a href="index.php?sala">Crear Sala</a>';
		}
		
		
		?>

	</nav>

	<main> 
		<section class="connect">
			
			<?php
				echo '<article>';
				
				if(isset($_GET['checkTime']) && ($_SESSION['user']->getName()!="")){
					echo '<a href="index.php?login&checkTime&close">Ocultar</a> <br/>';
					foreach($usersConectedInfo as $user){	
						echo '<a href="index.php?sala&privateChat='.$user->getId().'"> '.$user->getName().'🟢</a> </br>';
					}
				}
				else{
					echo  '<a href="index.php?login&checkTime">Conectados</a>';				
				}

				echo '</article>'; 
			
			?>

		</section>

		<nav>
		<?php

			if($salas>0 ){
				foreach($salas as $sala){	
					
					echo '<a href="index.php?sala&id_sala='.$sala->getIdSala().'"> '.$sala->getName().'</a>';
				}
			}
		?>
		</nav>
		
		<?php
		if(isset($_GET['sala'])){
		
		?>
		
		<section class="messages" >

			<?php
				if($salaById->getMessages() != null ){
					
					foreach($salaById->getMessages() as $message){
						
						if($message->getUser()->getId() == $_SESSION['user']->getId()){
							echo '<article id="emisor" style="margin-left: 50%">';
								echo '<b>'.$message->getUser().'</b>: '.$message->getMessage().' <span>'.$message->getDate().'</span>';
							echo '</article>'; 
						}
						else{
							echo '<article >';
								echo '<b>'.$message->getUser().'</b>: '.$message->getMessage().' <span>'.$message->getDate().'</span>';
							echo '</article>'; 
						}
					}
					
				}
				else{
					echo '<article>';
						echo 'no hay mensajes todavia';
					echo '</article>' ;
				}				
			?>

		</section>
	</main>
	<footer>
		<?php
		if($_SESSION['user']->getName()!=""){	
			echo '<form action="index.php?sala&id_sala='.$salaById->getIdSala().'" method="post">
			<input type="text" name="textChat" placeholder="habla..." required/>
			<input type="hidden" name="idSalaToMessage" value="'.$salaById->getIdSala().'" />
			<input type="submit" id="refresh" name="sendText" value="💬"/>
			</form>';
		}
	}
		?>
	</footer> 

</body>
</html>