<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="./css/mainView.css" >
	<title>Chat</title>
	<script>
	let refresh = document.getElementById('refresh');
	refresh.addEventListener('click', _ => {
            location.reload();
	})
</script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<style>
		header{
			text-align: center;
			font-size:20px
		}
		section{
			border: 1px solid black;
		}
		.connect{
			width : 100%;
			text-align: right;
		}
		nav a{
			padding:5px 50px;
			color: black;
			text-decoration:none;
		}
		form{
			padding-bottom: 10px;
		}
		article{
			padding: 5px;
			margin: 10px 0px;
			
		}
		article a{
			border : 1px solid black;
		}
		.chat {
		
			display: flex;
			flex-flow : row wrap;
			background-color: grey;
			justify-content : space-between;
		}
		.chat article{
			border-radius: 10px;
			width: 49%;
			background-color: lightgrey;
		}
		nav{
			background-color: grey;
			padding:5px;
			text-align:center;
		}
		footer{
			text-align: right;
			padding: 10px;
			background-color: grey;
		}
		footer form{
			
			margin-right: 0px;
		}	
		form input[type="text"]{
			width : 40%;
		}
		span{
			font-size:11px;
		}
	</style>
	
</head>
<body>

	<header>
		<h1>Chat</h1>
	</header>

	<nav>

		<a href="index.php">Inicio</a> -

		<?php
		//si la session existe
		if($_SESSION['user']->getName()=="")
			echo '<a href="index.php?login">Login</a>';
		else{
			echo 'Bienvenido '.$_SESSION['user']->getName().' 
			<a href="index.php?login&logout">Salir</a> -';
			
		}
		
		
		
		?>

	</nav>

	

	<section class="connect">
		
		<?php
		if($usersConected>0){
			echo '<article>';
			
			
			if(isset($_GET['infoConnectedUser'])){
				foreach($usersConectedInfo as $user){	
					echo $user->getName().'🟢';
				}
				echo '<a href="index.php?close">Ocultar</a>';
			}
			else{
				echo $usersConected;
				echo  '<a href="index.php?infoConnectedUser&close">Contectados</a>';
				
			}

			echo '</article>'; 
		}
		?>
	</section>

	<section class="chat">
		<?php
			
			if(($messages)>0){
				foreach($messages as $msg){
					echo '<article>';
						echo '<b>'.$msg->getUser().'</b>: '.$msg->getMessage().' <span>'.$msg->getDate().'</span>';
					echo '</article>'; 
				}
			}
			else{
				echo '<article>';
					echo 'no hay mensajes todavia';
				echo '</article>' ;
			}
							
		?>


	</section>

	<footer>
		<?php
		if($_SESSION['user']->getName()!=""){
					
			echo '<form action="index.php" method="post">
			<input type="text" name="textChat" placeholder="habla..." required/>
			<input type="submit" id="refresh" name="sendText" value="💬"/>
			</form>';

		}
			
		?>
	</footer>


</body>
</html>