<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/loginView.css" >
    <title>Crear sala</title>
	<link rel="stylesheet" href="./css/privateChat.css" >
   
   
</head>
<body>
    <header>
        <H1>Crea una sala</H1>
    </header>

    <nav>
        <a href="index.php">Inicio</a>
    </nav>

	<section >

		<?php
			if($chat->getMessages() != null ){
				
				foreach($chat->getMessages() as $message){
					
					if($message->getUser()->getId() == $_SESSION['user']->getId()){
						echo '<article id="emisor" style="margin-left: 50%">';
							echo '<b>'.$message->getUser().'</b>: '.$message->getMessage().' <span>'.$message->getDate().'</span>';
						echo '</article>'; 
					}
					else{
						echo '<article >';
							echo '<b>'.$message->getUser().'</b>: '.$message->getMessage().' <span>'.$message->getDate().'</span>';
						echo '</article>'; 
					}
				}
				
			}
			else{
				echo '<article>';
					echo 'no hay mensajes todavia';
				echo '</article>' ;
			}				
		?>
	</section>

	<footer>
		<?php
		if($_SESSION['user']->getName()!=""){	
			echo '<form  method="post">
			<input type="text" name="textChat" placeholder="habla..." required/>
			<input type="hidden" name="idChat" value="'.$chat->getIdChat().'" />
			<input type="submit" id="refresh" name="sendText" value="💬"/>
			</form>';

		}
		?>
	</footer> 
     
    
       
    
    </main>
	<!-- die(); -->
</body>
</html>