<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/loginView.css" >
    <title>Crear sala</title>
    <style>
        header{
			text-align: center;
			font-size:20px
		}
		section{
			border: 1px solid black;
		}
		.connect{
			width : 100%;
			text-align: right;
		}
		nav a{
			padding:5px 50px;
			color: black;
			text-decoration:none;
		}
		form{
			padding-bottom: 10px;
		}
		article{
			padding: 5px;
			margin: 10px 0px;
			
		}
		article a{
			border : 1px solid black;
		}
		.chat {
		
			display: flex;
			flex-flow : row wrap;
			background-color: grey;
			justify-content : space-between;
		}
		.chat article{
			border-radius: 10px;
			width: 49%;
			background-color: lightgrey;
		}
		nav{
			background-color: grey;
			padding:5px;
			text-align:center;
		}
		footer{
			text-align: right;
			padding: 10px;
			background-color: grey;
		}
		footer form{
			
			margin-right: 0px;
		}	
		form input[type="text"]{
			width : 40%;
		}
		span{
			font-size:11px;
		}
    </style>
</head>
<body>
    <header>
        <H1>Crea una sala</H1>
    </header>

    <nav>
        <a href="index.php">Inicio</a>
    </nav>


	

	<?php
	
	?>
	
	<section >

		<?php
			
			if($chat->getMessages() != null ){
				
				foreach($chat->getMessages() as $message){
					echo '<article>';
					echo '<b>'.$message->getUser().'</b>: '.$message->getMessage().' <span>'.$message->getDate().'</span>';
					echo '</article>'; 
					
				}
				
			}
			else{
				echo '<article>';
					echo 'no hay mensajes todavia';
				echo '</article>' ;
			}
							
		?>


	</section>

	<footer>
		<?php
		if($_SESSION['user']->getName()!=""){	
			echo '<form  method="post">
			<input type="text" name="textChat" placeholder="habla..." required/>
			<input type="hidden" name="idChat" value="'.$chat->getIdChat().'" />
			<input type="submit" id="refresh" name="sendText" value="💬"/>
			</form>';

		}
		?>
	</footer> 
     
    
       
    
    </main>
	<!-- die(); -->
</body>
</html>